-- MySQL Script generated by MySQL Workbench
-- 04/28/18 07:25:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Aseguradora36
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Aseguradora36
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aseguradora36` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Aseguradora36` ;

-- -----------------------------------------------------
-- Table `Aseguradora36`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aseguradora36`.`Cliente` (
  `Id_Cliente` INT NOT NULL,
  `Dirección` INT NOT NULL,
  `Nombre(s)` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aseguradora36`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aseguradora36`.`Factura` (
  `Id_Factura` INT NOT NULL,
  `Monto` DECIMAL NOT NULL,
  PRIMARY KEY (`Id_Factura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aseguradora36`.`Vehículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aseguradora36`.`Vehículo` (
  `Id_Placas` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Factura_Id_Factura` INT NOT NULL,
  PRIMARY KEY (`Id_Placas`, `Factura_Id_Factura`),
  INDEX `fk_Vehículo_Factura1_idx` (`Factura_Id_Factura` ASC),
  CONSTRAINT `fk_Vehículo_Factura1`
    FOREIGN KEY (`Factura_Id_Factura`)
    REFERENCES `Aseguradora36`.`Factura` (`Id_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aseguradora36`.`Poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aseguradora36`.`Poliza` (
  `Id_Poliza` INT NOT NULL,
  `Costo` DECIMAL(15,2) NOT NULL,
  `Prima_Asegurada` DECIMAL(15,2) NOT NULL,
  `Fecha_Apertura` DATE NOT NULL,
  `Fecha_Vencimiento` DATE NOT NULL,
  `Cliente_Id_Cliente` INT NOT NULL,
  `Vehículo_Id_Placas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Poliza`, `Cliente_Id_Cliente`, `Vehículo_Id_Placas`),
  INDEX `fk_Poliza_Cliente_idx` (`Cliente_Id_Cliente` ASC),
  INDEX `fk_Poliza_Vehículo1_idx` (`Vehículo_Id_Placas` ASC),
  CONSTRAINT `fk_Poliza_Cliente`
    FOREIGN KEY (`Cliente_Id_Cliente`)
    REFERENCES `Aseguradora36`.`Cliente` (`Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poliza_Vehículo1`
    FOREIGN KEY (`Vehículo_Id_Placas`)
    REFERENCES `Aseguradora36`.`Vehículo` (`Id_Placas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
